version: '1.0'
stages:
        - prepare
        - build

steps: 
        main_clone:
                title: Cloning main repository...
                stage: prepare
                type: git-clone
                repo: 'piotrowsianko/production_control_app'
                revision: dev-branch
                git: github
        build_my_image:
                title: Building Docker Image
                stage: build
                type: build
                image_name: my-django-image
                working_directory: ./
                tag: dev-branch
                dockerfile: Dockerfile

